services:
  - type: web
    name: mycarinfo-app
    runtime: docker
    dockerfilePath: ./MyCarInfo/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DisableHttpsRedirection
        value: "true"
      - key: DataProtection__KeysPath
        value: /var/mycarinfo/dpkeys
      - key: ConnectionStrings__DefaultConnection
        value: Server=tcp:mycarinfo-db,1433;Database=MyCarInfoDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False
    disk:
      name: mycarinfo-app-data
      mountPath: /var/mycarinfo
      sizeGB: 1

  - type: pserv
    name: mycarinfo-db
    runtime: docker
    image:
      url: mcr.microsoft.com/mssql/server:2022-latest
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: MSSQL_SA_PASSWORD
        value: YourStrong!Passw0rd
    disk:
      name: mycarinfo-sql-data
      mountPath: /var/opt/mssql
      sizeGB: 10
