version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mycarinfo-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycarinfo-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      DisableHttpsRedirection: "true"
      DataProtection__KeysPath: "/root/.aspnet/DataProtection-Keys"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=MyCarInfoDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False"
    ports:
      - "8080:8080"
    volumes:
      - app-dpkeys:/root/.aspnet/DataProtection-Keys

volumes:
  sql-data:
  app-dpkeys: